#pragma once
#include "CoreMinimal.h"
#include "GPPErrorCodes.generated.h"

UENUM()
enum class GPPErrorCodes {
    NoneError,
    StatusContinue = 100,
    StatusSwitchingProtocols,
    StatusProcessing,
    StatusOk = 200,
    StatusCreated,
    StatusAccepted,
    StatusNonAuthoritativeInfo,
    StatusNoContent,
    StatusResetContent,
    StatusPartialContent,
    StatusMultiStatus,
    StatusAlreadyReported,
    StatusImUsed = 226,
    StatusMultipleChoices = 300,
    StatusMovedPermanently,
    StatusFound,
    StatusSeeOther,
    StatusNotModified,
    StatusUseProxy,
    StatusTemporaryRedirect = 307,
    StatusPermanentRedirect,
    StatusBadRequest = 400,
    StatusUnauthorized,
    StatusPaymentRequired,
    StatusForbidden,
    StatusNotFound,
    StatusMethodNotAllowed,
    StatusNotAcceptable,
    StatusProxyAuthRequired,
    StatusRequestTimeout,
    StatusConflict,
    StatusGone,
    StatusLengthRequired,
    StatusPreconditionFailed,
    StatusRequestEntityTooLarge,
    StatusRequestUriTooLong,
    StatusUnsupportedMediaType,
    StatusRequestedRangeNotSatisfiable,
    StatusExpectationFailed,
    StatusTeapot,
    StatusMisdirectedRequest = 421,
    StatusUnprocessableEntity,
    StatusLocked,
    StatusFailedDependency,
    StatusUpgradeRequired = 426,
    StatusPreconditionRequired = 428,
    StatusTooManyRequests,
    StatusRequestHeaderFieldsTooLarge = 431,
    StatusUnavailableForLegalReasons = 451,
    StatusInternalServerError = 500,
    StatusNotImplemented,
    StatusBadGateway,
    StatusServiceUnavailable,
    StatusGatewayTimeout,
    StatusHttpVersionNotSupported,
    StatusVariantAlsoNegotiates,
    StatusInsufficientStorage,
    StatusLoopDetected,
    StatusNotExtended = 510,
    StatusNetworkAuthenticationRequired,
    AlreadyExistLinkedKIDByOtherPlatformAccount = 10173,
    GPPAccountDeletion = 7233,
    KraftonAccountDeletion = 7286,
    Login_AccountStatusChanged = 10146,
    GPPAccountBan = 10134,
    UserUnderAge = 10130,
    UnauthorizedException = 20001,
    GameRecordNotFoundException = 18003,
    PlayerRecordNotFoundException = 18022,
    GameRecordPreconditionFailedException = 18056,
    PlayerRecordPreconditionFailedException = 18103,
    PartyStorageOutdatedUpdateData = 119017,
    NeedRefreshAccessTokenFromLobby = 4001,
    DuplicatedSession = StatusConflict,
    KeepExistingMultiSession = 4005,
    RepaymentRequired = 1105020,
    AlreadyPurchased = 39177,
    CancelByUser = 100000001,
    NotFoundLastLoggedInfoFile,
    InvalidLastLoggedInfoFile,
    JsonDeserializationFailed,
    InvalidRequest,
    NetworkError,
    IsNotLoggedIn,
    WebSocketConnectFailed,
    UI_CreateFailed,
    ActiveMaintenance,
    GPPOSSAccountNotFound,
    WebViewNotExistCustomTab,
    InvalidResponse,
    AlreadyInitialized,
    ExpiredRefreshToken,
    Login_PlatformAuthTokenIsEmpty = 100001001,
    Login_InvalidateAuthPlatformLoginType,
    Login_PlatformLoginError,
    Login_WebViewCompleteError,
    Login_RetryLoginBySystem,
    Login_PlatformServerOauthFailed,
    Login_AlreadyLoggedIn,
    Login_AlreadyInProgress,
    Login_AccountBan,
    Login_KraftonAccountDeletion,
    Login_GPPAccountDeletion,
    Login_UserUnderAge,
    Login_PlatformAuthTokenTimeout,
    Login_PlatformAuthResponseInvalid,
    InvalidateAccount_Logout = 100002000,
    InvalidateAccount_RequestDeactivate,
    InvalidateAccount_DeleteAccountImmediately,
    InvalidateAccount_ExpiredRefreshToken,
    InvalidateAccount_UserIdChanged,
    LinkKID_InvalidateAuthPlatformLoginType = 100003000,
    LinkKID_AlreadyFullKIDOrNotLogin,
    LinkKID_NotSupportLinkLoginType,
    LinkKID_LinkGetAuthorizeWebURL,
    LinkKID_WebViewCompleteError,
    LinkKID_PlatformLoginError,
    Legal_BulkAcceptPolicyVersionError = 100004000,
    Legal_IsAcceptMandatoryLegalDocumentError,
    Store_UnknownError = 100005000,
    Store_NotInitialized,
    Store_UserNotLoggedIn,
    Store_TaskAlreadyRunning,
    Store_MethodNotImplemented,
    Store_InvalidProductId,
    Store_ProductPriceChanged,
    Store_SlowResponse,
    Store_PurchaseLimited,
    Store_InvalidServerResponse,
    Store_InvalidStore,
    Store_GooglePlayStoreResponsePositive = 100006000,
    Store_GooglePlayStoreResponse_USER_CANCELED,
    Store_GooglePlayStoreResponse_SERVICE_UNAVAILABLE,
    Store_GooglePlayStoreResponse_BILLING_UNAVAILABLE,
    Store_GooglePlayStoreResponse_ITEM_UNAVAILABLE,
    Store_GooglePlayStoreResponse_DEVELOPER_ERROR,
    Store_GooglePlayStoreResponse_ERROR,
    Store_GooglePlayStoreResponse_ITEM_ALREADY_OWNED,
    Store_GooglePlayStoreResponse_ITEM_NOT_OWNED,
    Store_GooglePlayStoreResponse_NETWORK_ERROR = 100006012,
    Store_GooglePlayStoreResponse_PENDING_PAYMENT = 100006099,
    Store_GooglePlayStoreResponseNegative,
    Store_GooglePlayStoreResponse_SERVICE_DISCONNECTED,
    Store_GooglePlayStoreResponse_FEATURE_NOT_SUPPORTED,
    Store_GooglePlayStoreResponse_SERVICE_TIMEOUT,
    Store_AppStoreResponseBase = 100007000,
    Store_AppStoreResponse_SKErrorClientInvalid,
    Store_AppStoreResponse_SKErrorPaymentCancelled,
    Store_AppStoreResponse_SKErrorPaymentInvalid,
    Store_AppStoreResponse_SKErrorPaymentNotAllowed,
    Store_AppStoreResponse_SKErrorStoreProductNotAvailable,
    Store_AppStoreResponse_SKErrorCloudServicePermissionDenied,
    Store_AppStoreResponse_SKErrorCloudServiceNetworkConnectionFailed,
    Store_AppStoreResponse_SKErrorCloudServiceRevoked,
    Store_AppStoreResponse_SKErrorUnknown = 100007999,
    Store_AppStoreResponse_PurchasePending = 100008801,
    Store_AppStoreResponse_CommonFailed = 100008900,
    Store_AppStoreResponse_JsonParsingFailed,
    Store_AppStoreResponse_RefreshFailed,
    Store_AppStoreResponse_VerifyFailed,
    Store_AppStoreResponse_UUIDParsingFailed,
    Store_AppStoreResponse_StoreFrontNotFound,
    Store_AppStoreResponse_SKErrorInvalidProductId = 100008999,
    Store_GalaxyStoreResponseBase = 100010000,
    Store_GalaxyStoreResponse_IAP_PAYMENT_IS_CANCELED,
    Store_GalaxyStoreResponse_IAP_ERROR_INITIALIZATION = 100011000,
    Store_GalaxyStoreResponse_IAP_ERROR_NEED_APP_UPGRADE,
    Store_GalaxyStoreResponse_IAP_ERROR_COMMON,
    Store_GalaxyStoreResponse_IAP_ERROR_ALREADY_PURCHASED,
    Store_GalaxyStoreResponse_IAP_ERROR_WHILE_RUNNING,
    Store_GalaxyStoreResponse_IAP_ERROR_PRODUCT_DOES_NOT_EXIST,
    Store_GalaxyStoreResponse_IAP_ERROR_CONFIRM_INBOX,
    Store_GalaxyStoreResponse_IAP_ERROR_ITEM_GROUP_DOES_NOT_EXIST,
    Store_GalaxyStoreResponse_IAP_ERROR_NETWORK_NOT_AVAILABLE,
    Store_GalaxyStoreResponse_IAP_ERROR_IOEXCEPTION_ERROR,
    Store_GalaxyStoreResponse_IAP_ERROR_SOCKET_TIMEOUT,
    Store_GalaxyStoreResponse_IAP_ERROR_CONNECT_TIMEOUT,
    Store_GalaxyStoreResponse_IAP_ERROR_NOT_EXIST_LOCAL_PRICE,
    Store_GalaxyStoreResponse_IAP_ERROR_NOT_AVAILABLE_SHOP,
    Store_GalaxyStoreResponse_IAP_ERROR_INVALID_ACCESS_TOKEN = 100011015,
    GameServerID_NotFoundGameServerID = 100012000,
    GameServerID_ActiveMaintenance,
    KCN_InvalidCode = 100014000,
    KCN_CodeIsEmpty,
    KCN_CodeLimitReached,
    CheckEligibility_UnderAge = 100015000,
    Lobby_MultiSessionLoginDetected = 200000001,
};

