#pragma once
#include "CoreMinimal.h"
#include "UWEBaseModuleRuleGenParams.generated.h"

USTRUCT(BlueprintType)
struct FUWEBaseModuleRuleGenParams {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool UseManualRules;
    
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool UseVertexColors;
    
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool SkipAutogen;
    
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool IgnoreAutogeneratedMatches;
    
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool IgnoreNormalsWhenMatching;
    
    UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
    bool InteriorModule;
    
    UPROPERTY(EditDefaultsOnly)
    bool Dirty;
    
    UWESCULPTURALBASE_API FUWEBaseModuleRuleGenParams();
};

