#pragma once
#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "UObject/NoExportTypes.h"
#include "UObject/NoExportTypes.h"
#include "GameFramework/Actor.h"
#include "Engine/HitResult.h"
#include "UWEDecorator.h"
#include "UWEBaseSupportActor.generated.h"

class AUWESculpturalBaseActor;
class UUWEBaseCellLockComponent;
class UUWESaveComponent;
class UUWESculpturalBaseModuleSettings;

UCLASS()
class UWESCULPTURALBASE_API AUWEBaseSupportActor : public AActor, public IUWEDecorator {
    GENERATED_BODY()
public:
    UPROPERTY(Replicated, SaveGame)
    FIntVector SupportCell;
    
protected:
    UPROPERTY(BlueprintReadOnly, SaveGame, ReplicatedUsing=OnRep_Position)
    FVector AttachPosition;
    
    UPROPERTY(BlueprintReadOnly, SaveGame, ReplicatedUsing=OnRep_Position)
    FVector EndPosition;
    
    UPROPERTY(BlueprintReadOnly, Replicated, SaveGame)
    bool HasFoundPostition;
    
    UPROPERTY()
    TWeakObjectPtr<AUWESculpturalBaseActor> base;
    
    UPROPERTY(SaveGame, ReplicatedUsing=OnRep_BaseGuid)
    FGuid BaseGUID;
    
    UPROPERTY(Instanced, Replicated)
    UUWEBaseCellLockComponent* EndLockComponent;
    
    UPROPERTY(BlueprintReadOnly, EditDefaultsOnly, Instanced)
    UUWESaveComponent* SaveComponent;
    
    UPROPERTY(Transient)
    UUWESculpturalBaseModuleSettings* CachedSettings;
    
    UPROPERTY(BlueprintReadOnly, EditDefaultsOnly)
    float SupportLength;
    
    UPROPERTY()
    bool IsDestroying;
    
    UPROPERTY()
    bool IsRefreshing;
    
    UPROPERTY(BlueprintReadOnly, EditDefaultsOnly)
    bool bMustBeOnGround;
    
    UPROPERTY(BlueprintReadOnly, EditDefaultsOnly)
    bool bMustBeOnBase;
    
public:
    AUWEBaseSupportActor(const FObjectInitializer& ObjectInitializer);

    virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintImplementableEvent)
    void UpdatePositions();
    
    UFUNCTION(BlueprintCallable)
    void SetAttachAndEndPoints(FVector Attach, FVector End, FHitResult EndHitResult);
    
    UFUNCTION()
    void RefreshEndSupport(bool EndIsSupported, FIntVector NewSupportCell);
    
protected:
    UFUNCTION()
    void OnRep_Position();
    
    UFUNCTION()
    void OnRep_BaseGuid();
    
public:
    UFUNCTION(BlueprintCallable, BlueprintImplementableEvent)
    void OnPositionsUpdated();
    
    UFUNCTION()
    void OnBasesReplicated();
    
protected:
    UFUNCTION()
    void OnBaseDestroyed(AActor* Actor);
    
public:
    UFUNCTION(BlueprintPure)
    static bool IsValidEndHit(const FHitResult& HitResult, bool& IgnoreHit, bool MustBeOnGround, bool MustBeOnBase);
    
    UFUNCTION()
    void InitializeAutoGenerated(AUWESculpturalBaseActor* InBase, FIntVector Cell);
    
    UFUNCTION()
    void Initialize();
    
    UFUNCTION(BlueprintNativeEvent, BlueprintPure)
    void GetTraceCheckData(FVector& LocalStart, FVector& LocalEnd) const;
    
    UFUNCTION(BlueprintPure)
    FIntVector GetSupportCell() const;
    
    UFUNCTION(BlueprintCallable)
    bool GetEndHit(FVector LocalStart, FVector LocalEnd, FHitResult& EndHit);
    
    UFUNCTION(BlueprintPure)
    AUWESculpturalBaseActor* GetBase() const;
    

    // Fix for true pure virtual functions not being implemented
};

