#include "MercunaNavLinkInfo.h"

FMercunaNavLinkInfo::FMercunaNavLinkInfo() {
    this->bIsAutoGenerated = false;
    this->bEnabled = false;
    this->TraversalType = EMercunaNavLinkTraversalType::OneWay;
    this->Cost = 0.00f;
    this->HeightMin = 0.00f;
    this->HeightMax = 0.00f;
}

