#include "MercunaGroundNavigationComponent.h"

UMercunaGroundNavigationComponent::UMercunaGroundNavigationComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
    this->NavGrid = NULL;
    this->bAutomaticSteeringParameters = true;
}

void UMercunaGroundNavigationComponent::UpdateDynamicSteeringParams(const FMercunaGroundNavigationDynamicSteeringParameters& NewDynamicSteeringParams) {
}

void UMercunaGroundNavigationComponent::TrackActor(AActor* Actor, float Distance, float Speed, FVector Offset, bool UsePartialPath) {
}

void UMercunaGroundNavigationComponent::Stop() {
}

void UMercunaGroundNavigationComponent::SteeringParametersChanged() {
}

void UMercunaGroundNavigationComponent::SetUsageSpec(FMercunaUsageSpec NewUsageSpec) {
}

void UMercunaGroundNavigationComponent::SetNavGridToBest() {
}

void UMercunaGroundNavigationComponent::SetNavGrid(AMercunaNavGroundGrid* NewNavGrid) {
}

void UMercunaGroundNavigationComponent::SetAvoidanceAgainst(AActor* Actor, bool Enable) {
}

void UMercunaGroundNavigationComponent::SetAgentType(FMercunaGroundAgentType NewAgentType) {
}

void UMercunaGroundNavigationComponent::ResumeNavigation() {
}

void UMercunaGroundNavigationComponent::PauseNavigation() {
}

bool UMercunaGroundNavigationComponent::OverrideSpeedMultiplier(const float NewSpeedMultiplier) {
    return false;
}

void UMercunaGroundNavigationComponent::NavLinkComplete() {
}

void UMercunaGroundNavigationComponent::MoveToLocations(const TArray<FVector>& Destinations, FVector EndDirection, float EndDistance, float Speed, bool UsePartialPath) {
}

void UMercunaGroundNavigationComponent::MoveToLocation(const FVector& Destination, FVector EndDirection, float EndDistance, float Speed, bool UsePartialPath) {
}

void UMercunaGroundNavigationComponent::MoveToActor(AActor* Actor, float EndDistance, float Speed, bool UsePartialPath) {
}

void UMercunaGroundNavigationComponent::InvalidateContextualSteeringParamsAgainstActor(AActor* Actor) {
}

void UMercunaGroundNavigationComponent::InvalidateContextualSteeringParams() {
}

FMercunaUsageSpec UMercunaGroundNavigationComponent::GetUsageSpec() const {
    return FMercunaUsageSpec{};
}

FMercunaGroundNavigationSteeringParameters UMercunaGroundNavigationComponent::GetSteeringParameters() const {
    return FMercunaGroundNavigationSteeringParameters{};
}

float UMercunaGroundNavigationComponent::GetRemainingPathLength() {
    return 0.0f;
}

EMerNavigationTrajectory UMercunaGroundNavigationComponent::GetPoseTrajectory(FPoseSearchQueryTrajectory& TrajectorySampleRange, float LookAhead, int32 SampleRate, bool ReturnAbsoluteTimes) const {
    return EMerNavigationTrajectory::Trajectory;
}

void UMercunaGroundNavigationComponent::GetPathInfo(bool& Valid, float& DistanceToEnd) {
}

void UMercunaGroundNavigationComponent::GetNextNavLinkInfo(bool& bNextNavLinkFound, float& DistanceToNextNavLink, float& TimeToNextNavLink, FMercunaPathNavLinkInfo& NavLinkInfo, float MaxLookAhead) const {
}

void UMercunaGroundNavigationComponent::GetNextNavLink(bool& bNextNavLinkFound, float& DistanceToNextNavLink, float& TimeToNextNavLink, FVector& TraversalStart, FVector& TraversalEnd, bool& bIsAutoGenerated, AActor*& NavLinkActor, UMercunaNavLinkComponent*& NavLinkComponent, FMercunaNavLinkInfo& AutoGeneratedNavLink, float MaxLookAhead) const {
}

AMercunaNavGroundGrid* UMercunaGroundNavigationComponent::GetNavGrid() const {
    return NULL;
}

FVector UMercunaGroundNavigationComponent::GetLookDirection() {
    return FVector{};
}

FMercunaGroundAgentType UMercunaGroundNavigationComponent::GetGroundAgentType() const {
    return FMercunaGroundAgentType{};
}

FMercunaGroundNavigationDynamicSteeringParameters UMercunaGroundNavigationComponent::GetDynamicSteeringParameters() const {
    return FMercunaGroundNavigationDynamicSteeringParameters{};
}

UMercunaPath* UMercunaGroundNavigationComponent::GetCurrentPath() {
    return NULL;
}

FMercunaGroundNavigationConfiguration UMercunaGroundNavigationComponent::GetConfiguration() const {
    return FMercunaGroundNavigationConfiguration{};
}

void UMercunaGroundNavigationComponent::ConfigureSteering(const FMercunaGroundNavigationSteeringParameters& NewSteering) {
}

void UMercunaGroundNavigationComponent::ConfigureMovement(EMercunaAvoidanceMode NewAvoidanceMode) {
}

void UMercunaGroundNavigationComponent::Configure(const FMercunaGroundNavigationConfiguration& NewConfiguration) {
}

void UMercunaGroundNavigationComponent::ClearAvoidanceExclusions() {
}

void UMercunaGroundNavigationComponent::CancelMovement() {
}

void UMercunaGroundNavigationComponent::AddDestinationLocation(FVector NextDestination, bool bSmoothTransition) {
}


