#include "MerNavGridRenderingComponent.h"

UMerNavGridRenderingComponent::UMerNavGridRenderingComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
    this->bDrawPolygons = true;
    this->bDrawUnseeded = false;
    this->bDrawPolygonLabels = false;
    this->bDrawGenerationBoxes = false;
    this->bDrawAutoGeneratedLinks = true;
    this->DrawDistance = 3200;
}


