#pragma once
#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "GameplayTagContainer.h"
#include "EMercunaNavLinkTraversalType.h"
#include "MercunaNavLinkIdentifier.h"
#include "MercunaUsageTypes.h"
#include "MercunaNavLinkInfo.generated.h"

class AActor;
class AMercunaNavGraph;
class UMercunaNavLinkComponent;

USTRUCT(BlueprintType)
struct MERCUNA_API FMercunaNavLinkInfo {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadOnly)
    FMercunaNavLinkIdentifier Identifier;
    
    UPROPERTY(BlueprintReadOnly)
    bool bIsAutoGenerated;
    
    UPROPERTY(BlueprintReadOnly)
    bool bEnabled;
    
    UPROPERTY(BlueprintReadOnly)
    EMercunaNavLinkTraversalType TraversalType;
    
    UPROPERTY(BlueprintReadOnly)
    FMercunaUsageTypes UsageTypes;
    
    UPROPERTY(BlueprintReadOnly)
    FGameplayTagContainer Tags;
    
    UPROPERTY(BlueprintReadOnly)
    FVector Start;
    
    UPROPERTY(BlueprintReadOnly)
    FVector End;
    
    UPROPERTY(BlueprintReadOnly)
    float Cost;
    
    UPROPERTY(BlueprintReadOnly)
    TSoftObjectPtr<AMercunaNavGraph> StartNavGrid;
    
    UPROPERTY(BlueprintReadOnly)
    TSoftObjectPtr<AMercunaNavGraph> EndNavGrid;
    
    UPROPERTY(BlueprintReadOnly)
    TWeakObjectPtr<AActor> NavLinkActor;
    
    UPROPERTY(BlueprintReadOnly, Export)
    TWeakObjectPtr<UMercunaNavLinkComponent> NavLinkComponent;
    
    UPROPERTY(BlueprintReadOnly)
    FVector StartHalfRail;
    
    UPROPERTY(BlueprintReadOnly)
    FVector EndHalfRail;
    
    UPROPERTY(BlueprintReadOnly)
    float HeightMin;
    
    UPROPERTY(BlueprintReadOnly)
    float HeightMax;
    
    FMercunaNavLinkInfo();
};

