#pragma once
#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "PoseSearch/PoseSearchTrajectoryTypes.h"
#include "EMerNavigationTrajectory.h"
#include "EMercunaAvoidanceMode.h"
#include "Mercuna2DNavigationComponent.h"
#include "MercunaGroundAgentType.h"
#include "MercunaGroundNavigationConfiguration.h"
#include "MercunaGroundNavigationDynamicSteeringParameters.h"
#include "MercunaGroundNavigationSteeringParameters.h"
#include "MercunaNavLinkInfo.h"
#include "MercunaPathNavLinkInfo.h"
#include "MercunaUsageSpec.h"
#include "MercunaGroundNavigationComponent.generated.h"

class AActor;
class AMercunaNavGroundGrid;
class UMercunaNavLinkComponent;
class UMercunaPath;

UCLASS(ClassGroup=Custom, meta=(BlueprintSpawnableComponent))
class MERCUNA_API UMercunaGroundNavigationComponent : public UMercuna2DNavigationComponent {
    GENERATED_BODY()
public:
    DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnSwimStopped);
    DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnSwimStarted);
    
    UPROPERTY(BlueprintAssignable)
    FOnSwimStarted OnSwimStarted;
    
    UPROPERTY(BlueprintAssignable)
    FOnSwimStopped OnSwimStopped;
    
protected:
    UPROPERTY(EditAnywhere)
    AMercunaNavGroundGrid* NavGrid;
    
    UPROPERTY(EditAnywhere)
    FMercunaGroundAgentType AgentType;
    
    UPROPERTY(BlueprintReadOnly, EditAnywhere)
    bool bAutomaticSteeringParameters;
    
    UPROPERTY(BlueprintReadOnly, EditAnywhere)
    FMercunaGroundNavigationSteeringParameters SteeringParameters;
    
    UPROPERTY(BlueprintReadOnly, EditAnywhere)
    FMercunaGroundNavigationConfiguration Configuration;
    
public:
    UMercunaGroundNavigationComponent(const FObjectInitializer& ObjectInitializer);

    UFUNCTION(BlueprintCallable)
    void UpdateDynamicSteeringParams(const FMercunaGroundNavigationDynamicSteeringParameters& NewDynamicSteeringParams);
    
    UFUNCTION(BlueprintCallable)
    void TrackActor(AActor* Actor, float Distance, float Speed, FVector Offset, bool UsePartialPath);
    
    UFUNCTION(BlueprintCallable)
    void Stop();
    
    UFUNCTION(BlueprintCallable)
    void SteeringParametersChanged();
    
    UFUNCTION(BlueprintCallable)
    void SetUsageSpec(FMercunaUsageSpec NewUsageSpec);
    
    UFUNCTION(BlueprintCallable)
    void SetNavGridToBest();
    
    UFUNCTION(BlueprintCallable)
    void SetNavGrid(AMercunaNavGroundGrid* NewNavGrid);
    
    UFUNCTION(BlueprintCallable)
    void SetAvoidanceAgainst(AActor* Actor, bool Enable);
    
    UFUNCTION(BlueprintCallable)
    void SetAgentType(FMercunaGroundAgentType NewAgentType);
    
    UFUNCTION(BlueprintCallable)
    void ResumeNavigation();
    
    UFUNCTION(BlueprintCallable)
    void PauseNavigation();
    
    UFUNCTION(BlueprintCallable)
    bool OverrideSpeedMultiplier(const float NewSpeedMultiplier);
    
    UFUNCTION(BlueprintCallable)
    void NavLinkComplete();
    
    UFUNCTION(BlueprintCallable)
    void MoveToLocations(const TArray<FVector>& Destinations, FVector EndDirection, float EndDistance, float Speed, bool UsePartialPath);
    
    UFUNCTION(BlueprintCallable)
    void MoveToLocation(const FVector& Destination, FVector EndDirection, float EndDistance, float Speed, bool UsePartialPath);
    
    UFUNCTION(BlueprintCallable)
    void MoveToActor(AActor* Actor, float EndDistance, float Speed, bool UsePartialPath);
    
    UFUNCTION(BlueprintCallable)
    void InvalidateContextualSteeringParamsAgainstActor(AActor* Actor);
    
    UFUNCTION(BlueprintCallable)
    void InvalidateContextualSteeringParams();
    
    UFUNCTION(BlueprintPure)
    FMercunaUsageSpec GetUsageSpec() const;
    
    UFUNCTION(BlueprintPure)
    FMercunaGroundNavigationSteeringParameters GetSteeringParameters() const;
    
    UFUNCTION(BlueprintCallable)
    float GetRemainingPathLength();
    
    UFUNCTION(BlueprintPure)
    EMerNavigationTrajectory GetPoseTrajectory(FPoseSearchQueryTrajectory& TrajectorySampleRange, float LookAhead, int32 SampleRate, bool ReturnAbsoluteTimes) const;
    
    UFUNCTION(BlueprintCallable)
    void GetPathInfo(bool& Valid, float& DistanceToEnd);
    
    UFUNCTION(BlueprintPure)
    void GetNextNavLinkInfo(bool& bNextNavLinkFound, float& DistanceToNextNavLink, float& TimeToNextNavLink, FMercunaPathNavLinkInfo& NavLinkInfo, float MaxLookAhead) const;
    
    UFUNCTION(BlueprintPure)
    void GetNextNavLink(bool& bNextNavLinkFound, float& DistanceToNextNavLink, float& TimeToNextNavLink, FVector& TraversalStart, FVector& TraversalEnd, bool& bIsAutoGenerated, AActor*& NavLinkActor, UMercunaNavLinkComponent*& NavLinkComponent, FMercunaNavLinkInfo& AutoGeneratedNavLink, float MaxLookAhead) const;
    
    UFUNCTION(BlueprintPure)
    AMercunaNavGroundGrid* GetNavGrid() const;
    
    UFUNCTION(BlueprintCallable)
    FVector GetLookDirection();
    
    UFUNCTION(BlueprintPure)
    FMercunaGroundAgentType GetGroundAgentType() const;
    
    UFUNCTION(BlueprintPure)
    FMercunaGroundNavigationDynamicSteeringParameters GetDynamicSteeringParameters() const;
    
    UFUNCTION(BlueprintCallable)
    UMercunaPath* GetCurrentPath();
    
    UFUNCTION(BlueprintPure)
    FMercunaGroundNavigationConfiguration GetConfiguration() const;
    
    UFUNCTION(BlueprintCallable)
    void ConfigureSteering(const FMercunaGroundNavigationSteeringParameters& NewSteering);
    
    UFUNCTION(BlueprintCallable)
    void ConfigureMovement(EMercunaAvoidanceMode NewAvoidanceMode);
    
    UFUNCTION(BlueprintCallable)
    void Configure(const FMercunaGroundNavigationConfiguration& NewConfiguration);
    
    UFUNCTION(BlueprintCallable)
    void ClearAvoidanceExclusions();
    
    UFUNCTION(BlueprintCallable)
    void CancelMovement();
    
    UFUNCTION(BlueprintCallable)
    void AddDestinationLocation(FVector NextDestination, bool bSmoothTransition);
    
};

