#pragma once
#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "MerGridEditorSettings.generated.h"

USTRUCT(BlueprintType)
struct FMerGridEditorSettings {
    GENERATED_BODY()
public:
    UPROPERTY(Config, EditAnywhere)
    FLinearColor NavigableColor;
    
    UPROPERTY(Config, EditAnywhere)
    FLinearColor AutoGeneratedLinkColor;
    
    UPROPERTY(Config, EditAnywhere)
    float VerticalOffset;
    
    UPROPERTY(Config, EditAnywhere)
    float LineThickness;
    
    MERCUNA_API FMerGridEditorSettings();
};

