#pragma once
#include "CoreMinimal.h"
#include "MerNavGraphRenderingComponent.h"
#include "MerNavGridRenderingComponent.generated.h"

UCLASS(ClassGroup=Custom, meta=(BlueprintSpawnableComponent))
class UMerNavGridRenderingComponent : public UMerNavGraphRenderingComponent {
    GENERATED_BODY()
public:
private:
    UPROPERTY(EditAnywhere)
    bool bDrawPolygons;
    
    UPROPERTY(EditAnywhere)
    bool bDrawUnseeded;
    
    UPROPERTY(EditAnywhere)
    bool bDrawPolygonLabels;
    
    UPROPERTY(EditAnywhere)
    bool bDrawGenerationBoxes;
    
    UPROPERTY(EditAnywhere)
    bool bDrawAutoGeneratedLinks;
    
    UPROPERTY(AdvancedDisplay, EditAnywhere)
    int32 DrawDistance;
    
public:
    UMerNavGridRenderingComponent(const FObjectInitializer& ObjectInitializer);

};

