#include "UWEBaseModuleRuleGenParams.h"

FUWEBaseModuleRuleGenParams::FUWEBaseModuleRuleGenParams() {
    this->UseManualRules = false;
    this->UseVertexColors = false;
    this->SkipAutogen = false;
    this->IgnoreAutogeneratedMatches = false;
    this->IgnoreNormalsWhenMatching = false;
    this->InteriorModule = false;
    this->Dirty = false;
}

