#include "UWEBaseSupportActor.h"
#include "UWESaveComponent.h"
#include "Net/UnrealNetwork.h"
#include "UWEBaseCellLockComponent.h"

AUWEBaseSupportActor::AUWEBaseSupportActor(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
    this->HasFoundPostition = false;
    this->EndLockComponent = CreateDefaultSubobject<UUWEBaseCellLockComponent>(TEXT("EndLockComponent"));
    this->SaveComponent = CreateDefaultSubobject<UUWESaveComponent>(TEXT("SaveComponent"));
    this->CachedSettings = NULL;
    this->SupportLength = 2000.00f;
    this->IsDestroying = false;
    this->IsRefreshing = false;
    this->bMustBeOnGround = false;
    this->bMustBeOnBase = false;
}


void AUWEBaseSupportActor::SetAttachAndEndPoints(FVector Attach, FVector End, FHitResult EndHitResult) {
}

void AUWEBaseSupportActor::RefreshEndSupport(bool EndIsSupported, FIntVector NewSupportCell) {
}

void AUWEBaseSupportActor::OnRep_Position() {
}

void AUWEBaseSupportActor::OnRep_BaseGuid() {
}


void AUWEBaseSupportActor::OnBasesReplicated() {
}

void AUWEBaseSupportActor::OnBaseDestroyed(AActor* Actor) {
}

bool AUWEBaseSupportActor::IsValidEndHit(const FHitResult& HitResult, bool& IgnoreHit, bool MustBeOnGround, bool MustBeOnBase) {
    return false;
}

void AUWEBaseSupportActor::InitializeAutoGenerated(AUWESculpturalBaseActor* InBase, FIntVector Cell) {
}

void AUWEBaseSupportActor::Initialize() {
}

void AUWEBaseSupportActor::GetTraceCheckData_Implementation(FVector& LocalStart, FVector& LocalEnd) const {
}

FIntVector AUWEBaseSupportActor::GetSupportCell() const {
    return FIntVector{};
}

bool AUWEBaseSupportActor::GetEndHit(FVector LocalStart, FVector LocalEnd, FHitResult& EndHit) {
    return false;
}

AUWESculpturalBaseActor* AUWEBaseSupportActor::GetBase() const {
    return NULL;
}

void AUWEBaseSupportActor::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    
    DOREPLIFETIME(AUWEBaseSupportActor, SupportCell);
    DOREPLIFETIME(AUWEBaseSupportActor, AttachPosition);
    DOREPLIFETIME(AUWEBaseSupportActor, EndPosition);
    DOREPLIFETIME(AUWEBaseSupportActor, HasFoundPostition);
    DOREPLIFETIME(AUWEBaseSupportActor, BaseGUID);
    DOREPLIFETIME(AUWEBaseSupportActor, EndLockComponent);
}


